# Site settings
title: Sammy Cheung
email: sammycheung@me.com
description: Sammy is ... my name.
baseurl: "/" 
url: "http://sammyc.tk" 
twitter_username: sammycheung
github_username:  iSammyC
files: '/path_to_your_files_folder/'

# Build settings
markdown: kramdown
